/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "pulse_out_aliases.h"
#include "pulse_out.h"
#include "operation_input_aliases.h"
#include "operation_input.h"
#include "sensor_left_aliases.h"
#include "sensor_left.h"
#include "sensor_right_aliases.h"
#include "sensor_right.h"
#include "direction_out_aliases.h"
#include "direction_out.h"
#include "VDAC8_1.h"
#include "Clock_1.h"
#include "leds_enable_aliases.h"
#include "leds_enable.h"
#include "Opamp_1.h"
#include "leds_control_aliases.h"
#include "leds_control.h"
#include "mp_led_aliases.h"
#include "mp_led.h"
#include "PWM_1.h"
#include "Clock_2.h"
#include "swt_from_sample_mode_aliases.h"
#include "swt_from_sample_mode.h"
#include "swt_to_sample_mode_aliases.h"
#include "swt_to_sample_mode.h"
#include "swt_mode_select_aliases.h"
#include "swt_mode_select.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

